version: '3'
services:
  nginx-ui:
    image: schenkd/nginx-ui:latest
    ports:
      - 18080:8080
    volumes:
     - nginx:/etc/nginx
  nginx:
    image: nginx:1.18.0-alpine
    ports:
      - 80:80
    volumes:
     - nginx:/etc/nginx

  nginx-webui:
    image: cym1102/nginxwebui:latest
    ports:
      - 28080:8080
    environment:
      - BOOT_OPTIONS=--server.port=8080

volumes:
  nginx: